import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually configured sidebar for explicit chapter navigation
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Chapter 1',
      collapsible: true,
      collapsed: false,
      items: ['chapter-1/overview'],
    },
    {
      type: 'category',
      label: 'Chapters',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapters',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Alternative: Use autogenerated sidebar
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */
};

export default sidebars;
